const app=document.getElementById("app");
const KEY="anatomiaStatsV1";
let state={topic:"Sistema locomotore",mode:"A · Identificazione libera",difficulty:2,count:5,custom:null,qIndex:0,results:[],questions:[],stats:loadStats()};
const synonymGroups={
"arco vertebrale":["arco vertebrale","arcus vertebrae","arco posteriore"],
"processo spinoso":["processo spinoso","processus spinosus","apofisi spinosa"],
"processo trasverso":["processo trasverso","processus transversus","apofisi trasversa"],
"forame vertebrale":["forame vertebrale","foramen vertebrale","foramen vertebrale"],
"corpo vertebrale":["corpo vertebrale","corpus vertebrae","corpo della vertebra"],
"processo articolare superiore":["processo articolare superiore","processus articularis superior","faccetta articolare superiore"],
"processo articolare inferiore":["processo articolare inferiore","processus articularis inferior","faccetta articolare inferiore"]
};
function norm(s){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim()}
function equivalent(a,b){const x=norm(a),y=norm(b);if(x===y)return true;for(const group of Object.values(synonymGroups)){if(group.some(v=>norm(v)===x)&&group.some(v=>norm(v)===y))return true}return false}
function loadStats(){try{return JSON.parse(localStorage.getItem(KEY))||{answered:0,correct:0,mistakes:{}}}catch{return{answered:0,correct:0,mistakes:{}}}}
function saveStats(){localStorage.setItem(KEY,JSON.stringify(state.stats))}
function layout(){app.innerHTML=`
<section class="hero"><div class="eyebrow">Pratica visuale · esame pratico</div><h1>Riconosci. Rispondi.<br>Correggi i tuoi errori.</h1><p>Un simulatore pensato per allenare il riconoscimento delle strutture anatomiche, con risposte libere, sinonimi anatomici e ripasso degli errori.</p></section>
<section class="panel">
<h2>1. Scegli l'argomento</h2><div class="grid" id="topics"></div>
<h2 class="section-title">2. Modalità</h2><div class="grid" id="modes"></div>
<h2 class="section-title">3. Difficoltà e numero</h2><div class="controls"><div class="field"><label>DIFFICOLTÀ</label><select id="diff"><option value="1">1 · Base</option><option value="2" selected>2 · Intermedia</option><option value="3">3 · Esame universitario</option><option value="4">4 · Avanzata</option></select></div><div class="field"><label>DOMANDE</label><select id="count"><option>5</option><option>10</option><option>15</option><option>20</option></select></div></div>
<h2 class="section-title">Atlante Anastasi</h2><div class="drop"><strong>Usa le tue immagini</strong><div class="muted">Carica una tavola/foto del tuo atlante per creare una domanda personalizzata direttamente nel browser.</div><input id="atlasFile" type="file" accept="image/*"></div>
<div class="start"><button class="btn gold" id="start">INIZIA SIMULAZIONE →</button></div>
</section>`;
renderChoices();document.getElementById("diff").onchange=e=>state.difficulty=+e.target.value;document.getElementById("count").onchange=e=>state.count=+e.target.value;
document.getElementById("atlasFile").onchange=handleAtlas;document.getElementById("start").onclick=startExam}
const topics=["Anatomia generale","Sistema locomotore","Colonna vertebrale","Arto superiore","Arto inferiore","Torace","Addome","Pelvi","Testa e collo","Sistema nervoso","Splancnologia","Anatomia topografica"];
const modes=["A · Identificazione libera","B · Guidata","C · Esame","D · Revisione errori","E · Random"];
function renderChoices(){document.getElementById("topics").innerHTML=topics.map(x=>`<button class="option ${x===state.topic?"active":""}" data-topic="${x}"><strong>${x}</strong><span>Riconoscimento visivo delle strutture</span></button>`).join("");document.querySelectorAll("[data-topic]").forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;renderChoices()});document.getElementById("modes").innerHTML=modes.map(x=>`<button class="option ${x===state.mode?"active":""}" data-mode="${x}"><strong>${x}</strong><span>${modeDesc(x)}</span></button>`).join("");document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;renderChoices()})}
function modeDesc(x){return x.startsWith("A")?"Nessun aiuto, risposta libera.":x.startsWith("B")?"Possibili risposte per orientarti.":x.startsWith("C")?"Simulazione d'esame: nessun aiuto.":x.startsWith("D")?"Fa ricomparire più spesso le strutture sbagliate.":"Selezione casuale di argomenti e strutture."}
function handleAtlas(e){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{state.custom={src:reader.result,name:f.name};alert("Immagine caricata. Nella prossima versione puoi anche costruire e salvare i punti direttamente sull'immagine.");};reader.readAsDataURL(f)}
function demoSvg(q){return `<svg viewBox="0 0 800 600" role="img" aria-label="Schema anatomico non etichettato"><rect x="0" y="0" width="800" height="600" rx="18" fill="#fbf8f4"/><g stroke="#4d3328" stroke-width="5" fill="#ead8c8"><path d="M300 115 C350 70 450 70 500 115 L470 175 C460 205 480 245 535 290 L585 340 C610 365 605 410 570 425 L505 452 C480 462 460 490 450 530 L350 530 C340 490 320 462 295 452 L230 425 C195 410 190 365 215 340 L265 290 C320 245 340 205 330 175 Z"/><ellipse cx="400" cy="255" rx="82" ry="55" fill="#fffdf9"/><path d="M318 185 L482 185 M290 325 L510 325 M255 390 L545 390" fill="none"/><path d="M400 110 L400 525" fill="none" stroke-width="3"/></g>${q.markers.map((m,i)=>`<line x1="${m.x}" y1="${m.y}" x2="${m.tx}" y2="${m.ty}" stroke="#9c342f" stroke-width="3"/><circle cx="${m.x}" cy="${m.y}" r="16" fill="#9c342f"/><text x="${m.x}" y="${m.y+6}" text-anchor="middle" font-size="16" font-weight="800" fill="white">${i+1}</text>`).join("")}<text x="400" y="570" text-anchor="middle" font-size="16" fill="#806e62">SCHEMA DIDATTICO · NON IN SCALA</text></svg>`}
const demoQuestions=[{topic:"Colonna vertebrale",title:"Vertebra cervicale — riconoscimento strutture",answers:["corpo vertebrale","forame vertebrale","processo spinoso","processo trasverso","arco vertebrale"],markers:[{x:280,y:165,tx:330,ty:205},{x:400,y:255,tx:400,ty:180},{x:535,y:290,tx:500,ty:340},{x:600,y:365,tx:530,ty:390},{x:330,y:455,tx:270,ty:430}]}];
function buildQuestions(){let pool=demoQuestions.filter(q=>state.topic==="Colonna vertebrale"||state.topic==="Sistema locomotore"||state.mode.startsWith("E"));if(!pool.length)pool=demoQuestions;let out=[];for(let i=0;i<state.count;i++)out.push(pool[i%pool.length]);return out}
function startExam(){state.qIndex=0;state.results=[];state.questions=buildQuestions();renderQuestion()}
function renderQuestion(){const q=state.questions[state.qIndex];const p=Math.round((state.qIndex/state.questions.length)*100);app.innerHTML=`<div class="exam-head"><div><div class="eyebrow">${state.topic} · ${state.mode}</div><h2>${q.title}</h2></div><div><b>${state.qIndex+1}/${state.questions.length}</b></div></div><div class="progress"><i style="width:${p}%"></i></div><div class="exam-grid"><div class="image-card">${state.custom&&state.qIndex===0?`<img src="${state.custom.src}" style="max-width:100%;max-height:650px" alt="Immagine caricata dall'utente">`:demoSvg(q)}</div><div class="answer-card"><h3>Identifica le strutture</h3><p class="muted">Osserva posizione e morfologia. Inserisci il nome anatomico; sono accettati sinonimi equivalenti.</p>${q.answers.map((a,i)=>`<div class="answer"><label>${i+1}. Struttura indicata</label><input autocomplete="off" data-answer="${i}" placeholder="Scrivi il nome..."></div>`).join("")}<div class="actions"><button class="btn gold" id="submit">CORREGGI</button><button class="btn light" id="home">Esci</button></div></div></div>`;document.getElementById("submit").onclick=()=>grade(q);document.getElementById("home").onclick=layout}
function grade(q){const inputs=[...document.querySelectorAll("[data-answer]")];const res=inputs.map((el,i)=>({answer:el.value.trim(),correct:equivalent(el.value,q.answers[i]),expected:q.answers[i]}));state.results.push(res);state.stats.answered+=res.length;res.forEach(r=>{if(r.correct)state.stats.correct++;else state.stats.mistakes[r.expected]=(state.stats.mistakes[r.expected]||0)+1});saveStats();renderCorrection(q,res)}
function renderCorrection(q,res){const score=res.filter(x=>x.correct).length;app.innerHTML=`<div class="panel"><div class="eyebrow">Correzione</div><div class="score">${score}/${res.length}</div><p class="muted">Ogni struttura è valutata separatamente.</p>${res.map((r,i)=>`<div class="result ${r.correct?"ok":"bad"}"><b>${r.correct?"✓":"✗"} ${i+1}. ${r.expected}</b><br>${r.correct?"Risposta riconosciuta corretta.":"Hai scritto: <em>"+(r.answer||"nessuna risposta")+"</em> · risposta corretta: <strong>"+r.expected+"</strong>"}</div>`).join("")}<div class="actions"><button class="btn gold" id="next">${state.qIndex+1<state.questions.length?"PROSSIMA DOMANDA →":"VEDI RISULTATI"}</button><button class="btn light" id="home">Torna al menu</button></div></div>`;document.getElementById("next").onclick=()=>{state.qIndex++;if(state.qIndex<state.questions.length)renderQuestion();else renderFinal()};document.getElementById("home").onclick=layout}
function renderFinal(){const total=state.results.flat().length,good=state.results.flat().filter(x=>x.correct).length;app.innerHTML=`<div class="panel"><div class="eyebrow">Simulazione terminata</div><h1>${good}/${total}</h1><p>Hai completato la sessione. Gli errori sono stati registrati localmente per la modalità revisione.</p><div class="actions"><button class="btn gold" id="again">Nuova simulazione</button><button class="btn light" id="stats">Statistiche</button></div></div>`;document.getElementById("again").onclick=layout;document.getElementById("stats").onclick=renderStats}
function renderStats(){const s=state.stats,acc=s.answered?Math.round(s.correct/s.answered*100):0;const mistakes=Object.entries(s.mistakes).sort((a,b)=>b[1]-a[1]);app.innerHTML=`<div class="panel"><div class="eyebrow">Progressi personali</div><h1>Statistiche</h1><div class="stats-row"><div class="stat"><span>Risposte</span><b>${s.answered}</b></div><div class="stat"><span>Corrette</span><b>${s.correct}</b></div><div class="stat"><span>Accuratezza</span><b>${acc}%</b></div><div class="stat"><span>Errori registrati</span><b>${Object.values(s.mistakes).reduce((a,b)=>a+b,0)}</b></div></div><h2 class="section-title">Strutture da ripassare</h2>${mistakes.length?mistakes.map(([k,v])=>`<div class="result bad"><b>${k}</b> · sbagliata ${v} volta/e</div>`).join(""):"<p class='muted'>Nessun errore registrato.</p>"}<div class="actions"><button class="btn gold" id="home">Torna al simulatore</button></div></div>`;document.getElementById("home").onclick=layout}
document.getElementById("statsBtn").onclick=renderStats;document.getElementById("resetBtn").onclick=()=>{if(confirm("Azzerare tutte le statistiche locali?")){localStorage.removeItem(KEY);state.stats=loadStats();layout()}};layout();